// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2dIMjXWA6sBkX_FL2vBfABHyzWM-23g',
    appId: '1:672058143276:web:7a6255cd216d9b60ad1789',
    messagingSenderId: '672058143276',
    projectId: 'test-fec05',
    authDomain: 'test-fec05.firebaseapp.com',
    databaseURL: 'https://test-fec05-default-rtdb.firebaseio.com',
    storageBucket: 'test-fec05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-mRVpJaDcaeHHOFzZrAPQDL-fUvWR08',
    appId: '1:672058143276:android:fc978901408fff26ad1789',
    messagingSenderId: '672058143276',
    projectId: 'test-fec05',
    databaseURL: 'https://test-fec05-default-rtdb.firebaseio.com',
    storageBucket: 'test-fec05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSGDU7ujZ_S3AysDRCJuBTODer9uEoiE',
    appId: '1:672058143276:ios:9892973b8163de9fad1789',
    messagingSenderId: '672058143276',
    projectId: 'test-fec05',
    databaseURL: 'https://test-fec05-default-rtdb.firebaseio.com',
    storageBucket: 'test-fec05.appspot.com',
    androidClientId: '672058143276-tqc8b1ak8dc1q1072c63ij3b00kdktg0.apps.googleusercontent.com',
    iosClientId: '672058143276-qsps6buurq9nh03otnjqv8pr7chlbkoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetest',
  );
}
